//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_Camera
    {
        public int ID { get; set; }

        [Display(Name = "摄像头名称")]
        public string CameraName { get; set; }

        [Display(Name = "关联设备")]
        public int DevId { get; set; }
        public string DnsAddr { get; set; }
        public string Port { get; set; }

        [Display(Name = "摄像头序列号")]
        public string UserName { get; set; }

        [Display(Name = "摄像头密码")]
        public string PassWord { get; set; }
        public int CameraId { get; set; }
        public string Type { get; set; }
    }
}
