//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Camera
    {
        public int ID { get; set; }
        public int DevId { get; set; }
        public string DnsAddr { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int CameraId { get; set; }
        public string Type { get; set; }
        public string CameraName { get; set; }
        public string Port { get; set; }
    }
}
