//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Devs
    {
        public int Id { get; set; }
        public string DevCode { get; set; }
        public string StatId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime PreEndTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public byte DevStatus { get; set; }
        public string VideoURL { get; set; }
    }
}
