//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ESDaytemp1
    {
        public long Id { get; set; }
        public string UpdateTime { get; set; }
        public int devID { get; set; }
        public Nullable<int> StatId { get; set; }
        public string Country { get; set; }
        public Nullable<double> TP { get; set; }
        public Nullable<double> DB { get; set; }
        public Nullable<double> WindSpeed { get; set; }
        public Nullable<double> WindDirection { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Humidity { get; set; }
    }
}
