//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Files
    {
        public int Id { get; set; }
        public Nullable<int> StatId { get; set; }
        public Nullable<System.DateTime> CapTime { get; set; }
        public Nullable<byte> Type { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
    }
}
