//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Files
    {
        public int Id { get; set; }
        public Nullable<int> StatId { get; set; }
        public Nullable<System.DateTime> CapTime { get; set; }
        public Nullable<byte> Type { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
    }
}
