//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Statistics
    {
        public int Id { get; set; }
        public Nullable<double> TP { get; set; }
        public Nullable<double> DB { get; set; }
        public Nullable<double> PM25 { get; set; }
        public Nullable<double> PM100 { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<short> type { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
