//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tasks
    {
        public long TaskId { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public int CmdType { get; set; }
        public int CmdByte { get; set; }
        public int DevId { get; set; }
        public byte[] Data { get; set; }
        public short Length { get; set; }
    }
}
