//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnicomScheduleConfig
    {
        public long Id { get; set; }
        public long ScheduleId { get; set; }
        public string DataName { get; set; }
        public double MaxValue { get; set; }
        public double MinValue { get; set; }
    }
}
