//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnicomDevice
    {
        public int Id { get; set; }
        public int DevId { get; set; }
        public double Max { get; set; }
        public double Min { get; set; }
        public bool OnCalc { get; set; }
        public string UnicomCode { get; set; }
        public int StatId { get; set; }
    }
}
