//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEP_Platform
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UnicomProject
    {
        public int Id { get; set; }
        public int StatId { get; set; }
        public string UnicomCode { get; set; }
        public bool Stopped { get; set; }
    }
}
