//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceExceptionChecker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Alarms
    {
        public int Id { get; set; }
        public Nullable<int> StatId { get; set; }
        public Nullable<int> DevId { get; set; }
        public Nullable<short> DustType { get; set; }
        public Nullable<double> FaultVal { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Country { get; set; }
        public bool IsReaded { get; set; }
    }
}
