//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceExceptionChecker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ESDaytemp1
    {
        public long Id { get; set; }
        public string UpdateTime { get; set; }
        public int devID { get; set; }
        public Nullable<int> StatId { get; set; }
        public string Country { get; set; }
        public Nullable<double> TP { get; set; }
        public Nullable<double> DB { get; set; }
        public Nullable<double> WindSpeed { get; set; }
        public Nullable<double> WindDirection { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Humidity { get; set; }
    }
}
