//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceExceptionChecker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Offset
    {
        public double OffSetCpm { get; set; }
        public double OffSetPlusCpm { get; set; }
        public double OffSetNoise { get; set; }
        public double OffSetPlusNoise { get; set; }
    }
}
