//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceExceptionChecker.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Photos
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public System.DateTime AddTime { get; set; }
        public string FileName { get; set; }
        public int DevId { get; set; }
    }
}
